services:
  # Development service - for running the application
  runner:
    build:
      context: .
      dockerfile: Dockerfile
      target: base  # Use minimal base stage (fast build)
    container_name: nv-lib-template-runner
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: bash -c "just run"
    stdin_open: true
    tty: true
    networks:
      - lib-network

  # Test service - for running tests
  tester:
    build:
      context: .
      dockerfile: Dockerfile
      target: base  # Use minimal base stage (fast build)
    container_name: nv-lib-template-tester
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: bash -c "just test"
    networks:
      - lib-network

volumes:
  dev-cache:
  test-cache:

networks:
  lib-network:
    driver: bridge
